services:
  ejs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ejs_signature_api
    ports:
      - "8001:8001"
    environment:
      - API_BEARER_TOKEN=test
    restart: unless-stopped